services:
  main-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8001:8001'
    restart: always
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo_db
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: