name: Deploy to Server

on:
  push:
    branches: ['master']
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.prettierrc'
      - '**/.env*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Save PEM key to file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | sed 's/\\n/\n/g' > /tmp/your-key.pem
          chmod 600 /tmp/your-key.pem

      - name: Debug Secrets
        run: |
          if [ -z "${{ secrets.EC2_PUBLIC_DNS }}" ]; then
            echo "❌ EC2_PUBLIC_DNS is NOT set!"
          else
            echo "✅ EC2_PUBLIC_DNS is set!"
          fi

          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then
            echo "❌ EC2_SSH_KEY is NOT set!"
          else
            echo "✅ EC2_SSH_KEY is set!"
          fi

          if [ -z "${{ secrets.ENV_VARIABLES }}" ]; then
            echo "❌ ENV_VARIABLES is NOT set!"
          else
            echo "✅ ENV_VARIABLES is set!"
          fi

      - name: SSH into EC2 and Deploy
        run: |
          ssh -i /tmp/your-key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            set -e  # Exit immediately if a command fails

            # Navigate to home directory
            cd /home/ubuntu

            # Check if the repository already exists
            if [ -d "assessment" ]; then
              echo "Repository exists. Pulling latest changes..."
              cd assessment
              git fetch origin
              git reset --hard origin/master
            else
              echo "Repository not found. Cloning..."
              git clone git@github.com:Rohit-saxena125/assessment.git
              cd assessment
            fi
            
            # Update the .env file correctly
            echo "${{ secrets.ENV_VARIABLES }}" | sed 's/\\n/\n/g' > .env
            # Deploy with Docker Compose
            docker-compose up -d --build
          EOF
